#!/usr/bin/env zsh

##? Clones a repo into /Volumes/SourceCode/Personal or /Volumes/SourceCode/Work
##? Usage: clone <repo> P[ersonal] | W[ork]

local dest repoName repoType
dest=$1
repoName=$(basename $dest .git)

# Set repo type
case $2 in
    P|p)
        repoType="Personal"
        ;;
    W|w)
        repoType="Work"
        ;;
    *)
        echo "Invalid repo type"
        exit 1
        ;;
esac

# Clone repo
git clone $dest /Volumes/SourceCode/$repoType/$repoName
